config/routes.rb
Rails.application.routes.draw do
  scope module: :neo_pixel do 
		resources :neo_pixels
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apiotics_setting.rb
class ApioticsSetting < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/neo_pixel.rb
module NeoPixel
  def self.table_name_prefix
    'neo_pixel_'
  end
  
  def self.sync_device_instances
    Apiotics.sync_device_instances(self.name)
  end
  
  def self.sync_devices
    Apiotics.sync_device_instances(self.name, true)
  end
    
end

app/models/neo_pixel/button.rb
module NeoPixel
  class Button < ApplicationRecord
    # The method(s) that correspond to device interfaces are: safe 
    
    has_many :button_safe_logs, dependent: :destroy
    
    belongs_to :neo_pixel
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    
  
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      Apiotics::Extract.send(self)
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.neo_pixel.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
    end
  
  end
end

app/models/neo_pixel/button_safe_log.rb
module NeoPixel
  class ButtonSafeLog < ApplicationRecord
  
  belongs_to :button
  
  end
end

app/models/neo_pixel/led.rb
module NeoPixel
  class Led < ApplicationRecord
    # The method(s) that correspond to device interfaces are: led_state 
    
    has_many :led_led_state_logs, dependent: :destroy
    
    belongs_to :neo_pixel
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    
  
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      Apiotics::Extract.send(self)
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.neo_pixel.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
    end
  
  end
end

app/models/neo_pixel/led_led_state_log.rb
module NeoPixel
  class LedLedStateLog < ApplicationRecord
  
  belongs_to :led
  
  end
end

app/models/neo_pixel/neo_pixel.rb
module NeoPixel
  class NeoPixel < ApplicationRecord
    
      
        has_one :led, dependent: :destroy
        accepts_nested_attributes_for :led
      
        has_one :button, dependent: :destroy
        accepts_nested_attributes_for :button
      
        has_one :neo_pixel_stick_eight, dependent: :destroy
        accepts_nested_attributes_for :neo_pixel_stick_eight
      
    
  end
end

app/models/neo_pixel/neo_pixel_stick_eight.rb
module NeoPixel
  class NeoPixelStickEight < ApplicationRecord
    # The method(s) that correspond to device interfaces are: led_index led_color 
    
    has_many :neo_pixel_stick_eight_led_index_logs, dependent: :destroy
    
    has_many :neo_pixel_stick_eight_led_color_logs, dependent: :destroy
    
    belongs_to :neo_pixel
    attr_accessor :skip_extract
    after_commit :extract, unless: :skip_extract
    after_commit :channel_push
    
    validates :led_index, inclusion: { in: 1..7,
    message: "%{value} is not within the range 1..7" }
  
    
    def sync
      Apiotics.sync(self)
    end
    
    private
  
    def extract
      Apiotics::Extract.send(self)
    end
    
    def channel_push
      if Apiotics.configuration.push == true
        interfaces = Hash.new
        puts self.previous_changes
        self.previous_changes.each do |k,v|
          if Apiotics::Extract.is_target(self, k)
            interfaces[k] = v[1].to_s
          end
        end
        interfaces.each do |k,v|
          ActionCable.server.broadcast "#{self.class.parent.to_s.underscore.downcase.gsub(" ", "_")}_channel",
            apiotics_instance: self.neo_pixel.apiotics_instance,
            worker_name: self.class.parent.to_s.underscore.downcase.gsub(" ", "_"),
            model_name: self.class.name.demodulize.to_s.underscore.downcase.gsub(" ", "_"),
            interface: k,
            value: v
        end
      end
    end
  
  end
end

app/models/neo_pixel/neo_pixel_stick_eight_led_color_log.rb
module NeoPixel
  class NeoPixelStickEightLedColorLog < ApplicationRecord
  
  belongs_to :neo_pixel_stick_eight
  
  end
end

app/models/neo_pixel/neo_pixel_stick_eight_led_index_log.rb
module NeoPixel
  class NeoPixelStickEightLedIndexLog < ApplicationRecord
  
  belongs_to :neo_pixel_stick_eight
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/neo_pixel/neo_pixels_controller.rb
module NeoPixel
  class NeoPixelsController < ApplicationController
    before_action :set_neo_pixel, only: [:show, :edit, :update, :destroy]

    # GET /alert/leds
    def index
      @neo_pixels = ::NeoPixel::NeoPixel.all
    end

    # GET /alert/leds/1
    def show
    end

    # GET /alert/leds/new
    def new
      redirect_to neo_pixels_url, notice: 'You are not authorized to do that.'
    end

    # GET /alert/leds/1/edit
    def edit
    end

    # POST /alert/leds
    def create
      @neo_pixel = ::NeoPixel::NeoPixel.new(neo_pixel_params)

      if @neo_pixel.save
        redirect_to neo_pixel_path(@neo_pixel), notice: 'NeoPixel was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /alert/leds/1
    def update
      if @neo_pixel.update(neo_pixel_params)
        redirect_to neo_pixel_path(@neo_pixel), notice: 'NeoPixel was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /alert/leds/1
    def destroy
      @neo_pixel.destroy
      redirect_to neo_pixels_url, notice: 'neo_pixel was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_neo_pixel
        @neo_pixel = ::NeoPixel::NeoPixel.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def neo_pixel_params
        params.fetch(:neo_pixel_neo_pixel, {}).permit(:id, :apiotics_instance, :led_attributes => ["led_state", "id"], :button_attributes => ["safe", "id"], :neo_pixel_stick_eight_attributes => ["led_index", "led_color", "id"])
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NeoLedTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/neo_pixel/neo_pixels/_form.html.erb
<%= simple_form_for(@neo_pixel, url: neo_pixel_path(@neo_pixel)) do |form| %>
  <table>
    <tr>
      <th>
        Id
      </th>
      <td>
        <%= @neo_pixel.apiotics_instance %>
      </td>
    </tr>
    <tr>
      <th>
        Name
      </th>
      <td>
          <%= @neo_pixel.name %>
      </td>
    </tr>
    
      <tr>
        <th rowspan='1'>
          Led
        </th>
        <%= form.simple_fields_for :led do |fields| %>
          
          
            
              <td>
                <%= fields.input :led_state %>
              </td>
            
            
          
        <% end %>
      </tr>
    
      <tr>
        <th rowspan='1'>
          Button
        </th>
        <%= form.simple_fields_for :button do |fields| %>
          
          
            
              <td>
                <%= fields.input :safe %>
              </td>
            
            
          
        <% end %>
      </tr>
    
      <tr>
        <th rowspan='2'>
          NeoPixelStickEight
        </th>
        <%= form.simple_fields_for :neo_pixel_stick_eight do |fields| %>
          
          
            
              <td>
                <%= fields.input :led_index %>
              </td>
            
            
          
            
              <tr>
            
              <td>
                <%= fields.input :led_color %>
              </td>
            
              </tr>
            
            
          
        <% end %>
      </tr>
    
      <tr>
        <th>
          &nbsp;
        </th>
        <td>
          <div class="actions">
            <%= form.submit %>
          </div>
        </td>
      </tr>
  </table>
<% end %>

app/views/neo_pixel/neo_pixels/edit.html.erb
<h1>Editing NeoPixel</h1>

<%= render 'form' %>

<%= link_to 'Show', neo_pixel_path(@neo_pixel) %> |
<%= link_to 'Back', neo_pixels_path %>

app/views/neo_pixel/neo_pixels/index.html.erb
<p id="notice"><%= notice %></p>
<h1>
  NeoPixels
</h1>

<table>
  <thead>
    <tr>
      <th style="border: 1px solid black;">
        Id
      </th>
      <th style="border: 1px solid black;">
        Name
      </th>
      
        <th colspan='1' style="border: 1px solid black;">
          Led
        </th>
      
        <th colspan='1' style="border: 1px solid black;">
          Button
        </th>
      
        <th colspan='2' style="border: 1px solid black;">
          NeoPixelStickEight
        </th>
      
      <th style="border: 1px solid black;">
        &nbsp;
      </th>
    </tr>
    <tr>
      <th>
        &nbsp;
      </th>
      <th>
        &nbsp;
      </th>
      
        
          <th>
            led_state
          </th>
        
      
        
          <th>
            safe
          </th>
        
      
        
          <th>
            led_index
          </th>
        
          <th>
            led_color
          </th>
        
      
      <th>
        &nbsp;
      </th>
    </tr>
  </thead>
  <tbody>
    <% @neo_pixels.each do |object| %>
      <tr id='<%= object.apiotics_instance %>'>
        <td>
          <%= object.apiotics_instance %>
        </td>
        <td>
          <%= object.name %>
        </td>
        
          
            <td class='neo_pixel-led-led_state'>
              <%= object.led.led_state %>
            </td>
          
        
          
            <td class='neo_pixel-button-safe'>
              <%= object.button.safe %>
            </td>
          
        
          
            <td class='neo_pixel-neo_pixel_stick_eight-led_index'>
              <%= object.neo_pixel_stick_eight.led_index %>
            </td>
          
            <td class='neo_pixel-neo_pixel_stick_eight-led_color'>
              <%= object.neo_pixel_stick_eight.led_color %>
            </td>
          
        
        <td>
          <%= link_to "Edit", edit_neo_pixel_path(object)%>
          <%= link_to "Show", neo_pixel_path(object) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/neo_pixel/neo_pixels/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  NeoPixel
</h1>
<table>
  <thead>
    <tr>
      <th style="border: 1px solid black;">
        Id
      </th>
      <th style="border: 1px solid black;">
        Name
      </th>
      
        <th colspan='1' style="border: 1px solid black;">
          Led
        </th>
      
        <th colspan='1' style="border: 1px solid black;">
          Button
        </th>
      
        <th colspan='2' style="border: 1px solid black;">
          NeoPixelStickEight
        </th>
      
    </tr>
    <tr>
      <th>
        &nbsp;
      </th>
      <th>
        &nbsp;
      </th>
      
        
          <th>
            led_state
          </th>
        
      
        
          <th>
            safe
          </th>
        
      
        
          <th>
            led_index
          </th>
        
          <th>
            led_color
          </th>
        
      
    </tr>
  </thead>
  <tbody>
    <tr id='<%= @neo_pixel.apiotics_instance %>'>
      <td>
        <%= @neo_pixel.apiotics_instance %>
      </td>
      <td>
        <%= @neo_pixel.name %>
      </td>
      
        
          <td class='neo_pixel-led-led_state'>
            <%= @neo_pixel.led.led_state %>
          </td>
        
      
        
          <td class='neo_pixel-button-safe'>
            <%= @neo_pixel.button.safe %>
          </td>
        
      
        
          <td class='neo_pixel-neo_pixel_stick_eight-led_index'>
            <%= @neo_pixel.neo_pixel_stick_eight.led_index %>
          </td>
        
          <td class='neo_pixel-neo_pixel_stick_eight-led_color'>
            <%= @neo_pixel.neo_pixel_stick_eight.led_color %>
          </td>
        
      
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_neo_pixel_path(@neo_pixel) %> |
<%= link_to 'Back', neo_pixels_path %>